namespace SatisfactoryPlanner.Modules.GameData.GameData
{
    public partial class Item
    { // Definitions of all the items--there are a lot so keeping it separate from the code of the class

        // Resources
        public static Item IronOre => new(ItemCategory.Resources, "IronOre", "Iron Ore", StackSize.Medium, ResourceForm.Solid, 1, 0, 0, 0, "Used for crafting.\r\nThe most essential basic resource.");
        public static Item CopperOre => new(ItemCategory.Resources, "CopperOre", "Copper Ore", StackSize.Medium, ResourceForm.Solid, 3, 0, 0, 0, "Used for crafting.\r\nA basic resource primarily used for electricity.");
        public static Item Limestone => new(ItemCategory.Resources, "Limestone", "Limestone", StackSize.Medium, ResourceForm.Solid, 2, 0, 0, 0, "Used for crafting.\r\nA basic resource primarily used for stable Foundations.");
        public static Item Coal => new(ItemCategory.Resources, "Coal", "Coal", StackSize.Medium, ResourceForm.Solid, 3, 300, 0, 0, "Mainly used as fuel for vehicles & Coal-Powered Generators, or in Steel production.");
        public static Item Sulfur => new(ItemCategory.Resources, "Sulfur", "Sulfur", StackSize.Medium, ResourceForm.Solid, 11, 0, 0, 0, "Primarily used to produce Black Powder.");
        public static Item RawQuartz => new(ItemCategory.Resources, "RawQuartz", "Raw Quartz", StackSize.Medium, ResourceForm.Solid, 15, 0, 0, 0, "Can be processed into Quartz Crystals and Silica, which both offer a variety of applications.");
        public static Item CateriumOre => new(ItemCategory.Resources, "CateriumOre", "Caterium Ore", StackSize.Medium, ResourceForm.Solid, 7, 0, 0, 0, "Smelted into Caterium Ingots, which are primarily used for advanced electronics.");
        public static Item Bauxite => new(ItemCategory.Resources, "Bauxite", "Bauxite", StackSize.Medium, ResourceForm.Solid, 8, 0, 0, 0, "Used to produce Alumina, which can be further refined into the Aluminum Scrap required to produce Aluminum Ingots.");
        public static Item Uranium => new(ItemCategory.Resources, "Uranium", "Uranium", StackSize.Medium, ResourceForm.Solid, 35, 0, 15, 0, "A radioactive element. \r\nUsed to produce Encased Uranium Cells for Uranium Fuel Rods.\r\n\r\nCaution: Moderately Radioactive.");
        public static Item SAM => new(ItemCategory.Resources, "SAM", "SAM", StackSize.Medium, ResourceForm.Solid, 20, 0, 0, 0, "Strange Alien Matter, commonly referred to as SAM, doesn't seem to follow the known laws of physics. It whispers of new possibilities.");
        public static Item Water => new(ItemCategory.Resources, "Water", "Water", StackSize.Fluid, ResourceForm.Liquid, 5, 0, 0, 0, "It's water.");
        public static Item CrudeOil => new(ItemCategory.Resources, "CrudeOil", "Crude Oil", StackSize.Fluid, ResourceForm.Liquid, 30, 0.32m, 0, 0, "Refined into all kinds of Oil-based resources, like Fuel and Plastic.");
        public static Item NitrogenGas => new(ItemCategory.Resources, "NitrogenGas", "Nitrogen Gas", StackSize.Fluid, ResourceForm.Gas, 10, 0, 0, 0, "Has a variety of uses, including metallurgy, cooling, and Nitric Acid production. On MASSAGE-2 (AB)b, it can be extracted from underground gas wells.");

        // Ingots
        public static Item IronIngot => new(ItemCategory.Ingots, "IronIngot", "Iron Ingot", StackSize.Medium, ResourceForm.Solid, 2, 0, 0, 0, "Used for crafting the most basic parts.");
        public static Item CopperIngot => new(ItemCategory.Ingots, "CopperIngot", "Copper Ingot", StackSize.Medium, ResourceForm.Solid, 6, 0, 0, 0, "Used for crafting the most basic parts.");
        public static Item SteelIngot => new(ItemCategory.Ingots, "SteelIngot", "Steel Ingot", StackSize.Medium, ResourceForm.Solid, 8, 0, 0, 0, "Smelted from a combination of Iron Ore and Coal. Can be made into several parts used in building construction.");
        public static Item CateriumIngot => new(ItemCategory.Ingots, "CateriumIngot", "Caterium Ingot", StackSize.Medium, ResourceForm.Solid, 42, 0, 0, 0, "Smelted from Caterium Ore. Primarily used for advanced electronics.");
        public static Item AluminumIngot => new(ItemCategory.Ingots, "AluminumIngot", "Aluminum Ingot", StackSize.Medium, ResourceForm.Solid, 131, 0, 0, 0, "Smelted from Aluminum Scrap, which is refined from Alumina Solution.\r\nUsed to produce specialized aluminum-based parts.");
        public static Item FicsiteIngot => new(ItemCategory.Ingots, "FicsiteIngot", "Ficsite Ingot", StackSize.Medium, ResourceForm.Solid, 1936, 0, 0, 0, "Produced by reconstructing other metals on a molecular level using Strange Alien Matter.\r\n\r\nSynthesized by FICSIT to be the perfect construction material, and used in the most high-end processes.");

        // Standard Parts
        public static Item IronRod => new(ItemCategory.StandardParts, "IronRod", "Iron Rod", StackSize.Big, ResourceForm.Solid, 4, 0, 0, 0, "Used for crafting.\r\nOne of the most basic parts.");
        public static Item IronPlate => new(ItemCategory.StandardParts, "IronPlate", "Iron Plate", StackSize.Big, ResourceForm.Solid, 6, 0, 0, 0, "Used for crafting.\r\nOne of the most basic parts.");
        public static Item ReinforcedIronPlate => new(ItemCategory.StandardParts, "ReinforcedIronPlate", "Reinforced Iron Plate", StackSize.Medium, ResourceForm.Solid, 120, 0, 0, 0, "Used for crafting.\r\nA sturdier and more durable Iron Plate.");
        public static Item Screws => new(ItemCategory.StandardParts, "Screws", "Screws", StackSize.Huge, ResourceForm.Solid, 2, 0, 0, 0, "Used for crafting.\r\nOne of the most basic parts.");
        public static Item ModularFrame => new(ItemCategory.StandardParts, "ModularFrame", "Modular Frame", StackSize.Small, ResourceForm.Solid, 408, 0, 0, 0, "Used for crafting.\r\nA multipurpose building block.");
        public static Item HeavyModularFrame => new(ItemCategory.StandardParts, "HeavyModularFrame", "Heavy Modular Frame", StackSize.Small, ResourceForm.Solid, 10800, 0, 0, 0, "A more robust multipurpose frame.");
        public static Item FusedModularFrame => new(ItemCategory.StandardParts, "FusedModularFrame", "Fused Modular Frame", StackSize.Small, ResourceForm.Solid, 62840, 0, 0, 0, "A corrosion-resistant, nitride-hardened, highly-robust-yet-lightweight modular frame.");
        public static Item SteelBeam => new(ItemCategory.StandardParts, "SteelBeam", "Steel Beam", StackSize.Big, ResourceForm.Solid, 64, 0, 0, 0, "Primarily used when constructing slightly more advanced buildings.");
        public static Item SteelPipe => new(ItemCategory.StandardParts, "SteelPipe", "Steel Pipe", StackSize.Big, ResourceForm.Solid, 24, 0, 0, 0, "Primarily used when constructing slightly more advanced buildings.");
        public static Item EncasedIndustrialBeam => new(ItemCategory.StandardParts, "EncasedIndustrialBeam", "Encased Industrial Beam", StackSize.Medium, ResourceForm.Solid, 528, 0, 0, 0, "Simultaneously utilizes the compressive strength of concrete and the tensile strength of steel.\r\nMostly used as a stable base for constructing buildings.");
        public static Item CopperSheet => new(ItemCategory.StandardParts, "CopperSheet", "Copper Sheet", StackSize.Big, ResourceForm.Solid, 24, 0, 0, 0, "Used for crafting.\r\nPrimarily used for Pipelines due to its high corrosion resistance.");
        public static Item AluminumCasing => new(ItemCategory.StandardParts, "AluminumCasing", "Aluminum Casing", StackSize.Big, ResourceForm.Solid, 393, 0, 0, 0, "A versatile container cast from Aluminum Ingots.");
        public static Item AlcladAluminumSheet => new(ItemCategory.StandardParts, "AlcladAluminumSheet", "Alclad Aluminum Sheet", StackSize.Big, ResourceForm.Solid, 266, 0, 0, 0, "Used to make products that require high heat conduction or a high specific strength. Thin, lightweight, and highly durable.");
        public static Item FicsiteTrigon => new(ItemCategory.StandardParts, "FicsiteTrigon", "Ficsite Trigon", StackSize.Big, ResourceForm.Solid, 1291, 0, 0, 0, "The Ficsite Trigon, made from Ficsite Ingots, is perfectly shaped for all construction challenges. Its performance is so exceptional, it basically solved structural engineering.");

        // Industrial Parts
        public static Item Rotor => new(ItemCategory.IndustrialParts, "Rotor", "Rotor", StackSize.Medium, ResourceForm.Solid, 140, 0, 0, 0, "Used for crafting.\r\nThe moving parts of a motor.");
        public static Item Stator => new(ItemCategory.IndustrialParts, "Stator", "Stator", StackSize.Medium, ResourceForm.Solid, 240, 0, 0, 0, "Used for crafting.\r\nThe static parts of a motor.");
        public static Item Motor => new(ItemCategory.IndustrialParts, "Motor", "Motor", StackSize.Small, ResourceForm.Solid, 1520, 0, 0, 0, "Creates a mechanical force that is used to move things from machines to vehicles.");
        public static Item HeatSink => new(ItemCategory.IndustrialParts, "HeatSink", "Heat Sink", StackSize.Medium, ResourceForm.Solid, 2804, 0, 0, 0, "Used to dissipate heat faster.");
        public static Item CoolingSystem => new(ItemCategory.IndustrialParts, "CoolingSystem", "Cooling System", StackSize.Medium, ResourceForm.Solid, 12006, 0, 0, 0, "Keeps advanced parts and buildings from exceeding efficient temperature levels.");
        public static Item TurboMotor => new(ItemCategory.IndustrialParts, "TurboMotor", "Turbo Motor", StackSize.Small, ResourceForm.Solid, 240496, 0, 0, 0, "A more complex and powerful version of the regular Motor.");
        public static Item Battery => new(ItemCategory.IndustrialParts, "Battery", "Battery", StackSize.Big, ResourceForm.Solid, 465, 6000, 0, 0, "Primarily used as fuel for Drones and vehicles.");

        // Compounds
        public static Item Concrete => new(ItemCategory.Compounds, "Concrete", "Concrete", StackSize.Huge, ResourceForm.Solid, 12, 0, 0, 0, "Used for building.\r\nGood for stable Foundations.");
        public static Item QuartzCrystal => new(ItemCategory.Compounds, "QuartzCrystal", "Quartz Crystal", StackSize.Big, ResourceForm.Solid, 50, 0, 0, 0, "Derived from Raw Quartz. Used in the production of advanced radar technology and high-quality display screens.");
        public static Item Silica => new(ItemCategory.Compounds, "Silica", "Silica", StackSize.Big, ResourceForm.Solid, 20, 0, 0, 0, "Derived from Raw Quartz. Commonly used to create glass structures, in advanced refinement processes, and for alternative production of electronics.");
        public static Item CompactedCoal => new(ItemCategory.Compounds, "CompactedCoal", "Compacted Coal", StackSize.Medium, ResourceForm.Solid, 28, 630, 0, 0, "A much more efficient alternative to Coal. Used as fuel for vehicles and Coal-Powered Generators.");
        public static Item CopperPowder => new(ItemCategory.Compounds, "CopperPowder", "Copper Powder", StackSize.Huge, ResourceForm.Solid, 72, 0, 0, 0, "Ground-up Copper Ingots.\r\nThe high natural density of Copper, combined with the granularity of the powder, makes this part perfect for producing Nuclear Pasta in the Particle Accelerator.");

        // Electronics
        public static Item Wire => new(ItemCategory.Electronics, "Wire", "Wire", StackSize.Huge, ResourceForm.Solid, 6, 0, 0, 0, "Used for crafting.\r\nOne of the most basic parts.");
        public static Item Cable => new(ItemCategory.Electronics, "Cable", "Cable", StackSize.Big, ResourceForm.Solid, 24, 0, 0, 0, "Used for crafting.\r\nPrimarily used to build Power Lines.");
        public static Item CircuitBoard => new(ItemCategory.Electronics, "CircuitBoard", "Circuit Board", StackSize.Big, ResourceForm.Solid, 696, 0, 0, 0, "Advanced electronics that have a plethora of different uses.");
        public static Item HighSpeedConnector => new(ItemCategory.Electronics, "HighSpeedConnector", "High-Speed Connector", StackSize.Medium, ResourceForm.Solid, 3776, 0, 0, 0, "Connects multiple cables and wires in a very efficient way. Uses a standard pattern, so it has many varied applications.");
        public static Item AILimiter => new(ItemCategory.Electronics, "AILimiter", "AI Limiter", StackSize.Medium, ResourceForm.Solid, 920, 0, 0, 0, "Controls AIs and keeps them from evolving in malicious ways. Super advanced electronics.");
        public static Item Quickwire => new(ItemCategory.Electronics, "Quickwire", "Quickwire", StackSize.Huge, ResourceForm.Solid, 17, 0, 0, 0, "Caterium's high conductivity and resistance to corrosion make it ideal for small, advanced electronics.");
        public static Item SingularityCell => new(ItemCategory.Electronics, "SingularityCell", "Singularity Cell", StackSize.Small, ResourceForm.Solid, 114675, 0, 0, 0, "Used to break down space and time. Required to power Portals.");
        public static Item ReanimatedSAM => new(ItemCategory.Electronics, "ReanimatedSAM", "Reanimated SAM", StackSize.Medium, ResourceForm.Solid, 160, 0, 0, 0, "The active and contained form of the Strange Alien Matter.\r\n\r\nProper electromagnetic containment is required, as it appears to be able to manipulate the atomic bonds of any matter it comes into contact with.");
        public static Item SAMFluctuator => new(ItemCategory.Electronics, "SAMFluctuator", "SAM Fluctuator", StackSize.Medium, ResourceForm.Solid, 1968, 0, 0, 0, "The SAM Fluctuator is able to regulate and direct the behavior of Reanimated SAM through the application of electric charges with varying frequencies.\r\nThis control facilitates technologies such as matter-to-energy conversion and spatiotemporal matter manipulation.");

        // Communications
        public static Item Computer => new(ItemCategory.Communications, "Computer", "Computer", StackSize.Small, ResourceForm.Solid, 8352, 0, 0, 0, "A complex logic machine that is used to control advanced behavior in other machines.");
        public static Item Supercomputer => new(ItemCategory.Communications, "Supercomputer", "Supercomputer", StackSize.Small, ResourceForm.Solid, 97352, 0, 0, 0, "The next-gen version of a Computer.");
        public static Item RadioControlUnit => new(ItemCategory.Communications, "RadioControlUnit", "Radio Control Unit", StackSize.Small, ResourceForm.Solid, 32352, 0, 0, 0, "Enhances and directs radio signals.");
        public static Item CrystalOscillator => new(ItemCategory.Communications, "CrystalOscillator", "Crystal Oscillator", StackSize.Medium, ResourceForm.Solid, 3072, 0, 0, 0, "An electronic oscillator circuit that uses the mechanical resonance of a vibrating crystal to create an electrical signal with a precise frequency.");

        // Oil Products
        public static Item PackagedOil => new(ItemCategory.OilProducts, "PackagedOil", "Packaged Oil", StackSize.Medium, ResourceForm.Solid, 180, 320, 0, 0, "Crude Oil, packaged for alternative transport. Can be used as fuel for vehicles.");
        public static Item Plastic => new(ItemCategory.OilProducts, "Plastic", "Plastic", StackSize.Big, ResourceForm.Solid, 75, 0, 0, 0, "Versatile and easy to manufacture, this material has a wide range of uses.");
        public static Item Rubber => new(ItemCategory.OilProducts, "Rubber", "Rubber", StackSize.Big, ResourceForm.Solid, 60, 0, 0, 0, "A very flexible material that has a lot of friction.");
        public static Item PolymerResin => new(ItemCategory.OilProducts, "PolymerResin", "Polymer Resin", StackSize.Big, ResourceForm.Solid, 12, 0, 0, 0, "A by-product of Crude Oil refinement into Fuel. Commonly used to manufacture Plastic and Rubber.");
        public static Item PetroleumCoke => new(ItemCategory.OilProducts, "PetroleumCoke", "Petroleum Coke", StackSize.Big, ResourceForm.Solid, 20, 180, 0, 0, "Used for crafting.\r\nA carbon-rich material distilled from Heavy Oil Residue. \r\nUsed as a less efficient Coal replacement.");
        public static Item HeavyOilResidue => new(ItemCategory.OilProducts, "HeavyOilResidue", "Heavy Oil Residue", StackSize.Fluid, ResourceForm.Liquid, 30, 0.4m, 0, 0, "A by-product of Plastic and Rubber production. Can be further refined into Fuel and Petroleum Coke.");
        public static Item PackagedHeavyOilResidue => new(ItemCategory.OilProducts, "PackagedHeavyOilResidue", "Packaged Heavy Oil Residue", StackSize.Medium, ResourceForm.Solid, 180, 400, 0, 0, "Heavy Oil Residue, packaged for alternative transport. Can be used as fuel for vehicles.");

        // Advanced Refinement
        public static Item AluminumScrap => new(ItemCategory.AdvancedRefinement, "AluminumScrap", "Aluminum Scrap", StackSize.Huge, ResourceForm.Solid, 27, 0, 0, 0, "Refined from Alumina. Can be smelted into Aluminum Ingots for industrial usage.");
        public static Item AluminaSolution => new(ItemCategory.AdvancedRefinement, "AluminaSolution", "Alumina Solution", StackSize.Fluid, ResourceForm.Liquid, 20, 0, 0, 0, "Dissolved Alumina, extracted from Bauxite. Can be further refined into Aluminum Scrap for Aluminum Ingot production.");
        public static Item PackagedAluminaSolution => new(ItemCategory.AdvancedRefinement, "PackagedAluminaSolution", "Packaged Alumina Solution", StackSize.Medium, ResourceForm.Solid, 160, 0, 0, 0, "Alumina Solution, packaged for alternative transport.");
        public static Item SulfuricAcid => new(ItemCategory.AdvancedRefinement, "SulfuricAcid", "Sulfuric Acid", StackSize.Fluid, ResourceForm.Liquid, 16, 0, 0, 0, "Produced by combining Sulfur and Water in a complex reaction. Primarily used in refinement processes and Battery production.");
        public static Item PackagedSulfuricAcid => new(ItemCategory.AdvancedRefinement, "PackagedSulfuricAcid", "Packaged Sulfuric Acid", StackSize.Medium, ResourceForm.Solid, 152, 0, 0, 0, "Sulfuric Acid, packaged for alternative transport.");
        public static Item NitricAcid => new(ItemCategory.AdvancedRefinement, "NitricAcid", "Nitric Acid", StackSize.Fluid, ResourceForm.Liquid, 94, 0, 0, 0, "Produced when Nitrogen Gas reacts with Water. Its high corrosiveness and oxidizing properties make it an excellent choice for refinement and fuel production processes.");
        public static Item PackagedNitricAcid => new(ItemCategory.AdvancedRefinement, "PackagedNitricAcid", "Packaged Nitric Acid", StackSize.Medium, ResourceForm.Solid, 412, 0, 0, 0, "Nitric Acid, packaged for alternative transport.");
        public static Item Diamonds => new(ItemCategory.AdvancedRefinement, "Diamonds", "Diamonds", StackSize.Big, ResourceForm.Solid, 240, 0, 0, 0, "Synthetic Diamonds produced by exposing Coal to extreme heat and pressure.\r\n\r\nUsed in the production of Time Crystals and Dark Matter Crystals.\r\n\r\nPower Usage: 250-750 MW (500 MW average).");
        public static Item DissolvedSilica => new(ItemCategory.AdvancedRefinement, "DissolvedSilica", "Dissolved Silica", StackSize.Fluid, ResourceForm.Liquid, 0, 0, 0, 0, "Silica dissolved in Water, produced as part of the alternative refinement of Raw Quartz.\r\nThe Silica can be extracted from the Water to complete the refinement process.");

        // Biomass
        public static Item Fabric => new(ItemCategory.Biomass, "Fabric", "Fabric", StackSize.Medium, ResourceForm.Solid, 140, 0, 0, 0, "Used to craft equipment.\r\nFlexible but durable fabric.");
        public static Item Wood => new(ItemCategory.Biomass, "Wood", "Wood", StackSize.Big, ResourceForm.Solid, 30, 100, 0, 0, "Primarily used as fuel.\r\nBiomass Burners and vehicles can use Wood for power.");
        public static Item Mycelia => new(ItemCategory.Biomass, "Mycelia", "Mycelia", StackSize.Big, ResourceForm.Solid, 10, 20, 0, 0, "Used for crafting.\r\nBiomass Burners and vehicles can also use Mycelia for power.");
        public static Item Leaves => new(ItemCategory.Biomass, "Leaves", "Leaves", StackSize.Huge, ResourceForm.Solid, 3, 15, 0, 0, "Primarily used as fuel.\r\nBiomass Burners and vehicles can use Leaves for power.");
        public static Item Biomass => new(ItemCategory.Biomass, "Biomass", "Biomass", StackSize.Big, ResourceForm.Solid, 12, 180, 0, 0, "Primarily used as fuel.\r\nBiomass Burners and vehicles can use it for power.\r\nBiomass is much more energy-efficient than raw biological matter.");
        public static Item SolidBiofuel => new(ItemCategory.Biomass, "SolidBiofuel", "Solid Biofuel", StackSize.Big, ResourceForm.Solid, 48, 450, 0, 0, "The most energy-efficient form of solid Biomass. Can be used as fuel for the Chainsaw.");

        // Fuel
        public static Item LiquidBiofuel => new(ItemCategory.Fuel, "LiquidBiofuel", "Liquid Biofuel", StackSize.Fluid, ResourceForm.Liquid, 261, 0.75m, 0, 0, "Liquid Biofuel can be used as-is to generate power, or packaged to be used as fuel for vehicles.");
        public static Item PackagedLiquidBiofuel => new(ItemCategory.Fuel, "PackagedLiquidBiofuel", "Packaged Liquid Biofuel", StackSize.Medium, ResourceForm.Solid, 370, 750, 0, 0, "Liquid Biofuel, packaged for alternative transport. Can be used as fuel for vehicles and the Jetpack.");
        public static Item Fuel => new(ItemCategory.Fuel, "Fuel", "Fuel", StackSize.Fluid, ResourceForm.Liquid, 75, 0.75m, 0, 0, "Can be used as-is to generate power, or packaged to be used as fuel for vehicles or the Jetpack.");
        public static Item PackagedFuel => new(ItemCategory.Fuel, "PackagedFuel", "Packaged Fuel", StackSize.Medium, ResourceForm.Solid, 270, 750, 0, 0, "Fuel, packaged for alternative transport. Can be used as fuel for vehicles and the Jetpack.");
        public static Item Turbofuel => new(ItemCategory.Fuel, "Turbofuel", "Turbofuel", StackSize.Fluid, ResourceForm.Liquid, 225, 2, 0, 0, "A more efficient alternative to Fuel. Can be used as-is to generate power, or packaged to be used as fuel for vehicles.");
        public static Item PackagedTurbofuel => new(ItemCategory.Fuel, "PackagedTurbofuel", "Packaged Turbofuel", StackSize.Medium, ResourceForm.Solid, 570, 2000, 0, 0, "Turbofuel, packaged for alternative transport. Can be used as fuel for vehicles and the Jetpack.");
        public static Item RocketFuel => new(ItemCategory.Fuel, "RocketFuel", "Rocket Fuel", StackSize.Fluid, ResourceForm.Gas, 289, 3.6m, 0, 0, "A high-impulse compressed gas fuel.\r\nCan be used as-is to power Fuel-Powered Generators, or packaged to be used as fuel for vehicles or the Jetpack.");
        public static Item PackagedRocketFuel => new(ItemCategory.Fuel, "PackagedRocketFuel", "Packaged Rocket Fuel", StackSize.Medium, ResourceForm.Solid, 1028, 7200m, 0, 0, "Rocket Fuel, packaged for alternative transport. Can be used as fuel for vehicles and the Jetpack.");
        public static Item IonizedFuel => new(ItemCategory.Fuel, "IonizedFuel", "Ionized Fuel", StackSize.Fluid, ResourceForm.Gas, 2398, 5m, 0, 0, "Fuel that has been ionized, allowing it to deliver incredible output.\r\nCan be used as-is to power Fuel-Powered Generators, or packaged to be used as fuel for vehicles or the Jetpack.");
        public static Item PackagedIonizedFuel => new(ItemCategory.Fuel, "PackagedIonizedFuel", "Packaged Ionized Fuel", StackSize.Medium, ResourceForm.Solid, 5246, 10000m, 0, 0, "Ionized Fuel, packaged for alternative transport. Can be used as fuel for vehicles and the Jetpack.");

        // Containers
        public static Item EmptyCanister => new(ItemCategory.Containers, "EmptyCanister", "Empty Canister", StackSize.Medium, ResourceForm.Solid, 60, 0, 0, 0, "Used to package fluids for transportation.");
        public static Item EmptyFluidTank => new(ItemCategory.Containers, "EmptyFluidTank", "Empty Fluid Tank", StackSize.Medium, ResourceForm.Solid, 170, 0, 0, 0, "Used to package gases and volatile liquids for transportation.");
        public static Item PressureConversionCube => new(ItemCategory.Containers, "PressureConversionCube", "Pressure Conversion Cube", StackSize.Small, ResourceForm.Solid, 255088, 0, 0, 0, "Converts outgoing force into internal pressure. Required to contain unstable, high-energy matter.");
        public static Item PackagedWater => new(ItemCategory.Containers, "PackagedWater", "Packaged Water", StackSize.Medium, ResourceForm.Solid, 130, 0, 0, 0, "Water, packaged for alternative transport."); // maybe standard parts? sf calc has it as containers
        public static Item PackagedNitrogenGas => new(ItemCategory.Containers, "PackagedNitrogenGas", "Packaged Nitrogen Gas", StackSize.Medium, ResourceForm.Solid, 312, 0, 0, 0, "Nitrogen Gas, packaged for alternative transport.");

        // Nuclear
        public static Item ElectromagneticControlRod => new(ItemCategory.Nuclear, "ElectromagneticControlRod", "Electromagnetic Control Rod", StackSize.Medium, ResourceForm.Solid, 2560, 0, 0, 0, "Regulates power output via electromagnetism.");
        public static Item EncasedUraniumCell => new(ItemCategory.Nuclear, "EncasedUraniumCell", "Encased Uranium Cell", StackSize.Big, ResourceForm.Solid, 147, 0, 0.5m, 0, "Used to produce Uranium Fuel Rods for Nuclear Power production. Made from Uranium Ore.\r\n\r\nCaution: Mildly Radioactive.");
        public static Item NonFissileUranium => new(ItemCategory.Nuclear, "NonFissileUranium", "Non-Fissile Uranium", StackSize.Huge, ResourceForm.Solid, 0, 0, 0.75m, 0, "The Uranium-238 isotope is non-fissile, meaning it cannot be used for nuclear fission. It can, however, be converted into fissile Plutonium in the Particle Accelerator.\r\n\r\nCaution: Mildly Radioactive.");
        public static Item UraniumFuelRod => new(ItemCategory.Nuclear, "UraniumFuelRod", "Uranium Fuel Rod", StackSize.Small, ResourceForm.Solid, 43468, 750000, 50, 0, "Used as fuel for Nuclear Power Plants.\r\n\r\nCaution: Produces radioactive Uranium Waste when consumed.\r\nCaution: Moderately Radioactive.");
        public static Item UraniumWaste => new(ItemCategory.Nuclear, "UraniumWaste", "Uranium Waste", StackSize.Huge, ResourceForm.Solid, 0, 0, 10, 0, "The by-product of consuming Uranium Fuel Rods in a Nuclear Power Plant.\r\nNon-Fissile Uranium can be extracted. Handle with caution.\r\n\r\nCaution: HIGHLY Radioactive.");
        public static Item PlutoniumPellet => new(ItemCategory.Nuclear, "PlutoniumPellet", "Plutonium Pellet", StackSize.Medium, ResourceForm.Solid, 0, 0, 20, 0, "Produced in the Particle Accelerator through conversion of Non-fissile Uranium.\r\nUsed to produce Encased Plutonium Cells for Plutonium Fuel Rods.\r\n\r\nPower Usage: 250-750 MW (500 MW average).\r\nCaution: Moderately Radioactive.");
        public static Item EncasedPlutoniumCell => new(ItemCategory.Nuclear, "EncasedPlutoniumCell", "Encased Plutonium Cell", StackSize.Big, ResourceForm.Solid, 0, 0, 120, 0, "Plutonium Pellets encased in concrete.\r\nUsed to produce Plutonium Fuel Rods for Nuclear Power production.\r\n\r\nPower Usage: 250-750 MW (500 MW average).\r\n﻿Caution: Moderately Radioactive.");
        public static Item PlutoniumFuelRod => new(ItemCategory.Nuclear, "PlutoniumFuelRod", "Plutonium Fuel Rod", StackSize.Small, ResourceForm.Solid, 153184, 1500000, 250, 0, "Used as fuel for Nuclear Power Plants.\r\n\r\nCaution: Produces radioactive Plutonium Waste when consumed.\r\nCaution: HIGHLY Radioactive.");
        public static Item PlutoniumWaste => new(ItemCategory.Nuclear, "PlutoniumWaste", "Plutonium Waste", StackSize.Huge, ResourceForm.Solid, 0, 0, 200, 0, "The by-product of consuming Plutonium Fuel Rods in a Nuclear Power Plant.\r\nMust be stored in a safe location. Handle with caution.\r\n\r\nCaution: EXTREMELY Radioactive.");
        public static Item Ficsonium => new(ItemCategory.Nuclear, "Ficsonium", "Ficsonium", StackSize.Medium, ResourceForm.Solid, 0, 0, 250, 0, "Usage and production of this material is strictly prohibited. On Earth, that is. There are no rules in space, only efficiency. \r\n\r\nPower Usage: 500-1500 MW (1000 MW average).\r\nCaution: Moderately Radioactive.");
        public static Item FicsoniumFuelRod => new(ItemCategory.Nuclear, "FicsoniumFuelRod", "Ficsonium Fuel Rod", StackSize.Small, ResourceForm.Solid, 0, 150000, 1000, 0, "Used as fuel for Nuclear Power Plants.\r\nThe power source that put FICSIT on the map. Literally. The crater is still there.\r\n\r\nCaution: Moderately Radioactive.");

        // Quantum Technology
        public static Item AlienPowerMatrix => new(ItemCategory.QuantumTechnology, "AlienPowerMatrix", "Alien Power Matrix", StackSize.Small, ResourceForm.Solid, 210, 0, 0, 0, "This intricate condensed-matter matrix is used to enhance the output of the Alien Power Augmenter.\r\n\r\nInitially developed in efforts to create a human-made Somersloop, the Alien Power Matrix cannot sustain the extra-dimensional energy connection on its own. However, it can effectively stabilize the energy stream of the Somersloop.");
        public static Item TimeCrystal => new(ItemCategory.QuantumTechnology, "TimeCrystal", "Time Crystal", StackSize.Big, ResourceForm.Solid, 960, 0, 0, 0, "Time Crystals are Diamonds that have been reconfigured on a sub-atomic level in the Converter to retain a time-periodic self-organizing structure. This allows them to be used in the development of quantum processing and storage technologies.");
        public static Item DarkMatterResidue => new(ItemCategory.QuantumTechnology, "DarkMatterResidue", "Dark Matter Residue", StackSize.Fluid, ResourceForm.Gas, 130, 0, 0, 0, "Produced as a by-product of Quantum Encoding processes and alternatively generated in the Converter.\r\n\r\nVarious fields of science are still debating the nature and properties of Dark Matter. Meanwhile, FICSIT has found several applications for it in space-time manipulation.");
        public static Item DarkMatterCrystal => new(ItemCategory.QuantumTechnology, "DarkMatterCrystal", "Dark Matter Crystal", StackSize.Big, ResourceForm.Solid, 1780, 0, 0, 0, "Concentrated Dark Matter Residue that is isolated within a crystalline vessel. This form of containment allows for utilising Dark Matter reliably in other production processes.\r\n\r\nPower Usage: 500-1500 MW (1000 MW average).");
        public static Item ExcitedPhotonicMatter => new(ItemCategory.QuantumTechnology, "ExcitedPhotonicMatter", "Excited Photonic Matter", StackSize.Fluid, ResourceForm.Gas, 100, 0, 0, 0, "Excited Photonic Matter is essential for all production processes in the Quantum Encoder.\r\n\r\nFormed in the Converter by inducing intense photon interactions through exposure to SAM in a high-energy environment.");
        public static Item SuperpositionOscillator => new(ItemCategory.QuantumTechnology, "SuperpositionOscillator", "Superposition Oscillator", StackSize.Medium, ResourceForm.Solid, 37292, 0, 0, 0, "An oscillator circuit that uses the mechanical resonance of a vibrating crystal to create a string vibration with a precise frequency. Often used in teleportation technology and dimensional manipulation.");
        public static Item NeuralQuantumProcessor => new(ItemCategory.QuantumTechnology, "NeuralQuantumProcessor", "Neural-Quantum Processor", StackSize.Medium, ResourceForm.Solid, 248034, 0, 0, 0, "The Neural-Quantum Processor utilizes a combination of neural network architecture and quantum computing techniques to achieve unprecedented performance. This technology has enabled some of FICSIT's biggest advancements in artificial intelligence and relativistic engineering.");

        // Space Elevator
        public static Item SmartPlating => new(ItemCategory.SpaceElevator, "SmartPlating", "Smart Plating", StackSize.Small, ResourceForm.Solid, 520, 0, 0, 0, "Project Part #1. Ship via the Space Elevator to complete phases of Project Assembly.");
        public static Item VersatileFramework => new(ItemCategory.SpaceElevator, "VersatileFramework", "Versatile Framework", StackSize.Small, ResourceForm.Solid, 1176, 0, 0, 0, "Project Part #2. Ship via the Space Elevator to complete phases of Project Assembly.");
        public static Item AutomatedWiring => new(ItemCategory.SpaceElevator, "AutomatedWiring", "Automated Wiring", StackSize.Small, ResourceForm.Solid, 1440, 0, 0, 0, "Project Part #3. Ship via the Space Elevator to complete phases of Project Assembly.");
        public static Item ModularEngine => new(ItemCategory.SpaceElevator, "ModularEngine", "Modular Engine", StackSize.Small, ResourceForm.Solid, 9960, 0, 0, 0, "Project Part #4. Ship via the Space Elevator to complete phases of Project Assembly.");
        public static Item AdaptiveControlUnit => new(ItemCategory.SpaceElevator, "AdaptiveControlUnit", "Adaptive Control Unit", StackSize.Small, ResourceForm.Solid, 76368, 0, 0, 0, "Project Part #5. Ship via the Space Elevator to complete phases of Project Assembly.");
        public static Item AssemblyDirectorSystem => new(ItemCategory.SpaceElevator, "AssemblyDirectorSystem", "Assembly Director System", StackSize.Small, ResourceForm.Solid, 500176, 0, 0, 0, "Project Part #6. Ship via the Space Elevator to complete phases of Project Assembly.\r\n\r\nThis extremely fast and precise computing system is specifically designed to direct the Project Assembly: Assembly Phase.");
        public static Item MagneticFieldGenerator => new(ItemCategory.SpaceElevator, "MagneticFieldGenerator", "Magnetic Field Generator", StackSize.Small, ResourceForm.Solid, 11000, 0, 0, 0, "Project Part #7. Ship via the Space Elevator to complete phases of Project Assembly.\r\n\r\nThese modular generators use superconducting magnets and vast amounts of electricity to produce a powerful and easily expandable magnetic field.");
        public static Item ThermalPropulsionRocket => new(ItemCategory.SpaceElevator, "ThermalPropulsionRocket", "Thermal Propulsion Rocket", StackSize.Small, ResourceForm.Solid, 728508, 0, 0, 0, "Project Part #8. Ship via the Space Elevator to complete phases of Project Assembly.\r\n\r\nUses extreme heat to produce the high-pressure plasma required to get Project Assembly into motion.");
        public static Item NuclearPasta => new(ItemCategory.SpaceElevator, "NuclearPasta", "Nuclear Pasta", StackSize.Small, ResourceForm.Solid, 538976, 0, 0, 0, "Project Part #9. Ship via the Space Elevator to complete phases of Project Assembly.\r\nPower Usage: 500-1500 MW (1000 MW average).\r\n\r\nNuclear Pasta is extremely dense degenerate matter, formed when extreme pressure forces protons and electrons together into neutrons. It is theorized to exist naturally within the crust of neutron stars.");
        public static Item BiochemicalSculptor => new(ItemCategory.SpaceElevator, "BiochemicalSculptor", "Biochemical Sculptor", StackSize.Small, ResourceForm.Solid, 301778, 0, 0, 0, "Project Part #10. Ship via the Space Elevator to complete phases of Project Assembly.\r\n\r\nYears ahead of the competition, this top-of-the-line 3D printer is used for the production of synthetic biological resources.");
        public static Item BallisticWarpDrive => new(ItemCategory.SpaceElevator, "BallisticWarpDrive", "Ballistic Warp Drive", StackSize.Small, ResourceForm.Solid, 2895334, 0, 0, 0, "Project Part #11. Ship via the Space Elevator to complete phases of Project Assembly.\r\n\r\nA large amount of force is required for the Warp Drives to activate, so sticking them to rockets was the logical next step. Additionally, results improved immensely when the observers were further removed from the Warp Drives upon activation.");
        public static Item AIExpansionServer => new(ItemCategory.SpaceElevator, "AIExpansionServer", "AI Expansion Server", StackSize.Small, ResourceForm.Solid, 597652, 0, 0, 0, "Project Part #12. Ship via the Space Elevator to complete phases of Project Assembly.\r\nPower Usage: 0-2000 MW (1000 MW average).\r\n\r\nGrowth is the metric by which we measure success.");

        // Consumables
        public static Item GasFilter => new(ItemCategory.Consumables, "GasFilter", "Gas Filter", StackSize.Small, ResourceForm.Solid, 608, 0, 0, 0, "Filters out toxins and pollutants from the air when used with a Gas Mask.");
        public static Item IodineInfusedFilter => new(ItemCategory.Consumables, "IodineInfusedFilter", "Iodine-Infused Filter", StackSize.Small, ResourceForm.Solid, 2274, 0, 0, 0, "Absorbs radioactive particles when used with the Hazmat Suit.");
        public static Item BerylNut => new(ItemCategory.Consumables, "BerylNut", "Beryl Nut", StackSize.Medium, ResourceForm.Solid, 0, 0, 0, 5, "Consumable\r\n\r\nEat to restore half a health segment.");
        public static Item MedicinalInhaler => new(ItemCategory.Consumables, "MedicinalInhaler", "Medicinal Inhaler", StackSize.Small, ResourceForm.Solid, 125, 0, 0, 100, "Fully restores health when used.\r\n\r\nThe FICSIT Medicinal Inhaler can be produced from a variety of different ingredients.");
        public static Item BaconAgaric => new(ItemCategory.Consumables, "BaconAgaric", "Bacon Agaric", StackSize.Small, ResourceForm.Solid, 0, 0, 0, 20, "Consumable\r\n\r\nEat to restore 2 health segments.");
        public static Item Paleberry => new(ItemCategory.Consumables, "Paleberry", "Paleberry", StackSize.Small, ResourceForm.Solid, 0, 0, 0, 10, "Consumable\r\n\r\nEat to restore 1 health segment.");

        // Tools 
        public static Item PortableMiner => new(ItemCategory.Tools, "PortableMiner", "Portable Miner", StackSize.Small, ResourceForm.Solid, 56, 0, 0, 0, "Automatically extracts a resource when placed on a resource node.\r\nNote: Has limited storage space.");
        public static Item Chainsaw => new(ItemCategory.Tools, "Chainsaw", "Chainsaw", StackSize.One, ResourceForm.Solid, 2760, 0, 0, 0, "Clears an area of flora that is too difficult to remove by hand.\r\n\r\nFuel: Biofuel");
        public static Item ObjectScanner => new(ItemCategory.Tools, "ObjectScanner", "Object Scanner", StackSize.One, ResourceForm.Solid, 1400, 0, 0, 0, "Scans the area for a selected item. Beeps at a rate proportional to proximity and direction.");
        public static Item Zipline => new(ItemCategory.Tools, "Zipline", "Zipline", StackSize.One, ResourceForm.Solid, 5284, 0, 0, 0, "Provides faster traversal of factories by allowing pioneers to zip along Power lines.\r\nActivate the Zipline and aim at a nearby Power Line to connect to it.");
        public static Item FactoryCart => new(ItemCategory.Tools, "FactoryCart", "Factory Cart™", StackSize.One, ResourceForm.Solid, 1552, 0, 0, 0, "The one and only FICSIT Factory Cart™.\r\nNow with special FICSIT-Foundation-only Grip Wheels, for an even smoother and faster factory floor experience!");
        public static Item GoldenFactoryCart => new(ItemCategory.Tools, "GoldenFactoryCart", "Golden Factory Cart™", StackSize.One, ResourceForm.Solid, 1852, 0, 0, 0, "The one and only Golden FICSIT Factory Cart™\r\n\r\nYou have now officially ascended. \r\nGo forth now, Master of Spaghetti, God of the Factory, Sinker of Cups, Employee of the Planet... travel in STYLE!");

        // Body Equipment
        public static Item Parachute => new(ItemCategory.BodyEquipment, "Parachute", "Parachute", StackSize.One, ResourceForm.Solid, 6080, 0, 0, 0, "Slows down your fall when activated in mid-air.");
        public static Item Hoverpack => new(ItemCategory.BodyEquipment, "Hoverpack", "Hoverpack", StackSize.One, ResourceForm.Solid, 265632, 0, 0, 0, "Power Consumption: 100 MW\r\n\r\nAllows pioneers to move vertically and hover in mid-air to improve building efficiency and factory traversal. Wirelessly connects to nearby power connections, such as Power Poles and Buildings, for power consumption.\r\n\r\nSlow-Fall: Hold {PlayerMovement_Jump} after losing connection mid-air.\r\nDisable Hoverpack: Double tap {PlayerMovement_Crouch} while hovering.");
        public static Item HazmatSuit => new(ItemCategory.BodyEquipment, "HazmatSuit", "Hazmat Suit", StackSize.One, ResourceForm.Solid, 54100, 0, 0, 0, "Shields pioneers from the adverse effects of radiation. \r\nConsumes Iodine-Infused Filters from the pioneer's inventory when worn in radioactive areas.");
        public static Item GasMask => new(ItemCategory.BodyEquipment, "GasMask", "Gas Mask", StackSize.One, ResourceForm.Solid, 14960, 0, 0, 0, "Allows pioneers to breathe normally in toxic gas-filled areas.\r\nConsumes Gas Filters from the pioneer's inventory when in use.");
        public static Item Jetpack => new(ItemCategory.BodyEquipment, "Jetpack", "Jetpack", StackSize.One, ResourceForm.Solid, 16580, 0, 0, 0, "Allows pioneers to travel through the air with increased control.\r\n\r\nFuel is automatically consumed from the pioneer's inventory to refill the Jetpack while on the ground.\r\nDifferent fuel types can be used and provide different levels of Jetpack efficiency. The preferred fuel type will be used if available, and can be set in the equipment inventory.");
        public static Item BladeRunners => new(ItemCategory.BodyEquipment, "BladeRunners", "Blade Runners", StackSize.One, ResourceForm.Solid, 4088, 0, 0, 0, "An exoskeleton for the lower legs that assists movement, allowing pioneers to sprint faster and jump higher.\r\nAlso dampens the impact of landing.");

        // Weapons
        public static Item XenoZapper => new(ItemCategory.Weapons, "XenoZapper", "Xeno-Zapper", StackSize.One, ResourceForm.Solid, 1880, 0, 0, 0, "A standard issue self-defense electroshock melee weapon.");
        public static Item XenoBasher => new(ItemCategory.Weapons, "XenoBasher", "Xeno-Basher", StackSize.One, ResourceForm.Solid, 17800, 0, 0, 0, "A heavy self-defense electroshock melee weapon.");
        public static Item RebarGun => new(ItemCategory.Weapons, "RebarGun", "Rebar Gun", StackSize.One, ResourceForm.Solid, 1968, 0, 0, 0, "An improvised ranged weapon for self-defense. Has to be reloaded after each use.");
        public static Item Rifle => new(ItemCategory.Weapons, "Rifle", "Rifle", StackSize.One, ResourceForm.Solid, 9480, 0, 0, 0, "A long-range, rapid-fire weapon. Specifically designed to deliver adequate performance within the designated work area.");
        public static Item NobeliskDetonator => new(ItemCategory.Weapons, "NobeliskDetonator", "Nobelisk Detonator", StackSize.One, ResourceForm.Solid, 6480, 0, 0, 0, "A remote-control device used to handle and detonate Nobelisks.");

        //Ammunition
        public static Item BlackPowder => new(ItemCategory.Ammunition, "BlackPowder", "Black Powder", StackSize.Big, ResourceForm.Solid, 14, 0, 0, 0, "An explosive powder that is commonly used to produce simple explosives.");
        public static Item SmokelessPowder => new(ItemCategory.Ammunition, "SmokelessPowder", "Smokeless Powder", StackSize.Medium, ResourceForm.Solid, 58, 0, 0, 0, "An explosive powder that is commonly used to produce modern firearms.");
        public static Item IronRebar => new(ItemCategory.Ammunition, "IronRebar", "Iron Rebar", StackSize.Medium, ResourceForm.Solid, 8, 0, 0, 0, "Can be shot using the Rebar Gun for self-defense purposes.");
        public static Item ExplosiveRebar => new(ItemCategory.Ammunition, "ExplosiveRebar", "Explosive Rebar", StackSize.Medium, ResourceForm.Solid, 360, 0, 0, 0, "Explodes on impact, dealing heavy damage.");
        public static Item ShatterRebar => new(ItemCategory.Ammunition, "ShatterRebar", "Shatter Rebar", StackSize.Medium, ResourceForm.Solid, 332, 0, 0, 0, "Fractures when shot, launching deadly debris with wide spread but limited range.");
        public static Item StunRebar => new(ItemCategory.Ammunition, "StunRebar", "Stun Rebar", StackSize.Medium, ResourceForm.Solid, 186, 0, 0, 0, "Electrocutes the target on impact, stunning it for a short time.\r\n\r\nStun Duration: 5 seconds");
        public static Item RifleAmmo => new(ItemCategory.Ammunition, "RifleAmmo", "Rifle Ammo", StackSize.Huge, ResourceForm.Solid, 25, 0, 0, 0, "Standard issue Rifle ammunition, useful for establishing dominance.");
        public static Item HomingRifleAmmo => new(ItemCategory.Ammunition, "HomingRifleAmmo", "Homing Rifle Ammo", StackSize.Huge, ResourceForm.Solid, 855, 0, 0, 0, "The bullet guidance system built into this ammunition allows it to accurately hit any target within the reticle area.\r\nEspecially useful when dealing with agile threats, or for pioneers who can't be bothered to aim properly.");
        public static Item TurboRifleAmmo => new(ItemCategory.Ammunition, "TurboRifleAmmo", "Turbo Rifle Ammo", StackSize.Huge, ResourceForm.Solid, 120, 0, 0, 0, "Lightweight, compact, and volatile. These rounds provide extreme capacity and rate of fire at the cost of accuracy.");
        public static Item Nobelisk => new(ItemCategory.Ammunition, "Nobelisk", "Nobelisk", StackSize.Small, ResourceForm.Solid, 152, 0, 0, 0, "A simple explosive, useful for clearing boulders, vegetation, and other obstacles.");
        public static Item ClusterNobelisk => new(ItemCategory.Ammunition, "ClusterNobelisk", "Cluster Nobelisk", StackSize.Small, ResourceForm.Solid, 1376, 0, 0, 0, "Detonates into multiple smaller explosions. Practical for clearing out large areas of vegetation and other inconveniences.");
        public static Item GasNobelisk => new(ItemCategory.Ammunition, "GasNobelisk", "Gas Nobelisk", StackSize.Small, ResourceForm.Solid, 544, 0, 0, 0, "Creates a deadly gas cloud instead of a regular explosion.");
        public static Item NukeNobelisk => new(ItemCategory.Ammunition, "NukeNobelisk", "Nuke Nobelisk", StackSize.Small, ResourceForm.Solid, 19600, 0, 0, 0, "Uses a nuclear fission reaction to generate a massive explosion.\r\nWARNING: Ensure all FICSIT property is clear of the blast zone before detonation.\r\n");
        public static Item PulseNobelisk => new(ItemCategory.Ammunition, "PulseNobelisk", "Pulse Nobelisk", StackSize.Small, ResourceForm.Solid, 1533, 0, 0, 0, "Generates a powerful shockwave instead of a regular explosion.");

        // Alien Remains
        public static Item HogRemains => new(ItemCategory.AlienRemains, "HogRemains", "Hog Remains", StackSize.Small, ResourceForm.Solid, 0, 0, 0, 0, "The carapace of an alien Hog creature.\r\nUsed for MAM research.");
        public static Item HatcherRemains => new(ItemCategory.AlienRemains, "HatcherRemains", "Hatcher Remains", StackSize.Small, ResourceForm.Solid, 0, 0, 0, 0, "The shell-like remains of an alien... thing.\r\nUsed for MAM research.");
        public static Item SpitterRemains => new(ItemCategory.AlienRemains, "SpitterRemains", "Spitter Remains", StackSize.Small, ResourceForm.Solid, 0, 0, 0, 0, "The remains of a plasma-spitting alien creature.\r\nUsed for MAM research.");
        public static Item StingerRemains => new(ItemCategory.AlienRemains, "StingerRemains", "Stinger Remains", StackSize.Small, ResourceForm.Solid, 0, 0, 0, 0, "The remains of whatever that creepy thing was.\r\nUsed for MAM research.");
        public static Item AlienProtein => new(ItemCategory.AlienRemains, "AlienProtein", "Alien Protein", StackSize.Medium, ResourceForm.Solid, 0, 0, 0, 0, "Ground-up Alien Remains in a neat little package.\r\nUsed for medical purposes and to research alien organisms.");
        public static Item AlienDNACapsule => new(ItemCategory.AlienRemains, "AlienDNACapsule", "Alien DNA Capsule", StackSize.Small, ResourceForm.Solid, 0, 0, 0, 0, "Translates organic chemicals into readable alien genetic information.\r\nUsed for researching alien organisms.\r\n\r\nGo the extra kilometer! Knowledge is power, and power is just efficiency with fewer steps. Depositing Alien DNA Capsules in the AWESOME Sink provides FICSIT with knowledge, and pioneers with Coupons.");

        // Power Shards
        public static Item BluePowerSlug => new(ItemCategory.PowerShards, "BluePowerSlug", "Blue Power Slug", StackSize.Small, ResourceForm.Solid, 0, 0, 0, 0, "A strange slug radiating an unknown weak power.");
        public static Item YellowPowerSlug => new(ItemCategory.PowerShards, "YellowPowerSlug", "Yellow Power Slug", StackSize.Small, ResourceForm.Solid, 0, 0, 0, 0, "A strange slug radiating an unknown power.");
        public static Item PurplePowerSlug => new(ItemCategory.PowerShards, "PurplePowerSlug", "Purple Power Slug", StackSize.Small, ResourceForm.Solid, 0, 0, 0, 0, "A strange slug radiating a powerful unknown power.");
        public static Item PowerShard => new(ItemCategory.PowerShards, "PowerShard", "Power Shard", StackSize.Medium, ResourceForm.Solid, 0, 0, 0, 0, "Power Slug mucus compressed into a solid crystal-like shard. \r\nIt radiates a strange power.");

        // FICSMAS
        public static Item FICSMASGift => new(ItemCategory.FICSMAS, "FICSMASGift", "FICSMAS Gift", StackSize.Big, ResourceForm.Solid, 1, 0, 0, 0, "Gifts that have inexplicably fallen from the sky or spawned from a FICSMAS Gift Tree.\r\n\r\nDon’t question it—they’re used to produce FICSMAS buildings and parts.\r\n\r\nThese Gifts are part of the FICSMAS Event, like the calendar in the HUB.");
        public static Item RedFICSMASOrnament => new(ItemCategory.FICSMAS, "RedFICSMASOrnament", "Red FICSMAS Ornament", StackSize.Big, ResourceForm.Solid, 2, 0, 0, 0, "An ornament for making FICSMAS Decorations. An acceptable red.");
        public static Item BlueFICSMASOrnament => new(ItemCategory.FICSMAS, "BlueFICSMASOrnament", "Blue FICSMAS Ornament", StackSize.Big, ResourceForm.Solid, 1, 0, 0, 0, "An ornament for making FICSMAS Decorations. A mildly pleasing blue.");
        public static Item CopperFICSMASOrnament => new(ItemCategory.FICSMAS, "CopperFICSMASOrnament", "Copper FICSMAS Ornament", StackSize.Medium, ResourceForm.Solid, 32, 0, 0, 0, "An ornament for making FICSMAS Decorations. A slightly dignified copper.");
        public static Item IronFICSMASOrnament => new(ItemCategory.FICSMAS, "IronFICSMASOrnament", "Iron FICSMAS Ornament", StackSize.Medium, ResourceForm.Solid, 18, 0, 0, 0, "An ornament for making FICSMAS Decorations. An okay iron.");
        public static Item FICSMASOrnamentBundle => new(ItemCategory.FICSMAS, "FICSMASOrnamentBundle", "FICSMAS Ornament Bundle", StackSize.Medium, ResourceForm.Solid, 100, 0, 0, 0, "A collection of FICSMAS ornaments and also an eyesore.");
        public static Item FICSMASWreath => new(ItemCategory.FICSMAS, "FICSMASWreath", "FICSMAS Wreath", StackSize.Small, ResourceForm.Solid, 630, 0, 0, 0, "FICSIT's newest holiday innovation: decorations that can be turned into decorations! Efficiency and waste-conscious design at its best.");
        public static Item FICSMASActualSnow => new(ItemCategory.FICSMAS, "FICSMASActualSnow", "FICSMAS Actual Snow", StackSize.Huge, ResourceForm.Solid, 5, 0, 0, 0, "This Actual Snow is made from several chemical elements and experiences 100% like naturally occuring snow after extensive user testing.");
        public static Item Snowball => new(ItemCategory.FICSMAS, "Snowball", "Snowball", StackSize.Medium, ResourceForm.Solid, 30, 0, 0, 0, "Compressed dihydrogen monoxide crystals for weaponized fun!");
        public static Item FICSMASBow => new(ItemCategory.FICSMAS, "FICSMASBow", "FICSMAS Bow", StackSize.Medium, ResourceForm.Solid, 4, 0, 0, 0, "A fancy bow. Not for wearing, eating, admiring, Lizard Doggos, humans, aliens, or anything not related to FICSMAS factory production.");
        public static Item FICSMASTreeBranch => new(ItemCategory.FICSMAS, "FICSMASTreeBranch", "FICSMAS Tree Branch", StackSize.Huge, ResourceForm.Solid, 2, 0, 0, 0, "This FICSMAS Tree Branch is very different from regular tree branches: it's used to produce parts and buildings during the FICSMAS event, rather than for combustion.");
        public static Item FICSMASWonderStar => new(ItemCategory.FICSMAS, "FICSMASWonderStar", "FICSMAS Wonder Star", StackSize.Small, ResourceForm.Solid, 6540, 0, 0, 0, "A symbol of appreciation for all the hard work FICSIT has done for its employees. It seems to have an aura of gratitude. Seeing this also means the seasonal event is nearly done, and we can finally get back to Saving The Day.");
        public static Item CandyCane => new(ItemCategory.FICSMAS, "CandyCane", "Candy Cane", StackSize.Medium, ResourceForm.Solid, 6, 0, 0, 0, "A delicious Candy Cane to be enjoyed during the FICSMAS Holidays.\r\n*Disclaimer: Not for human consumption...");
        public static Item CandyCaneBasher => new(ItemCategory.FICSMAS, "CandyCaneBasher", "Candy Cane Basher", StackSize.One, ResourceForm.Solid, 7850, 0, 0, 0, "Self-defense is now not only fun, but also delicious for the target! Do not lick or consume.");
        public static Item SweetFireworks => new(ItemCategory.Ammunition, "SweetFireworks", "Sweet Fireworks", StackSize.Medium, ResourceForm.Solid, 60, 0, 0, 0, "Has the minimum safety requirements.");
        public static Item FancyFireworks => new(ItemCategory.Ammunition, "FancyFireworks", "Fancy Fireworks", StackSize.Medium, ResourceForm.Solid, 40, 0, 0, 0, "Poses acceptable amount of risk to pioneers.");
        public static Item SparklyFireworks => new(ItemCategory.Ammunition, "SparklyFireworks", "Sparkly Fireworks", StackSize.Medium, ResourceForm.Solid, 32, 0, 0, 0, "Keep away from easily distracted pioneers.");
    }
}
