CREATE OR REPLACE VIEW resources.v_world_nodes
AS

SELECT
	WORLD_NODE.ID,
	WORLD_NODE.WORLD_ID,
	(
		CASE
			WHEN WORLD_NODE.EXTRACTOR_ID IS NULL THEN FALSE
			ELSE TRUE
		END
	) AS IS_TAPPED,
	WORLD_NODE.EXTRACTOR_ID,
	WORLD_NODE.EXTRACTION_RATE,
	NODE.ID AS NODE_ID,
	RESOURCE.NAME || ' - ' || NODE.BIOME || ' ' || NODE.NUMBER AS NODE_NAME,
	NODE.PURITY AS NODE_PURITY,
	NODE.BIOME AS NODE_BIOME,
	NODE.NUMBER AS NODE_NUMBER,
	RESOURCE.ID AS RESOURCE_ID,
	RESOURCE.NAME AS RESOURCE_NAME
FROM
	RESOURCES.WORLD_NODES AS WORLD_NODE
	INNER JOIN RESOURCES.NODES AS NODE ON NODE.ID = WORLD_NODE.NODE_ID
	INNER JOIN RESOURCES.RESOURCES AS RESOURCE ON RESOURCE.ID = NODE.RESOURCE_ID