# Triggered whenever a pull request is made to run the Nuke build script.

name: CI Pipeline

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened

jobs:
  tests:
    name: Build and run tests

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
  
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: | 
          6.0.x
          8.0.x

    - name: Run build
      run: ./build.sh RunCIBuild --configuration Release
