# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: CI Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build and run Unit and Architecture Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Cache .nuke/temp, ~/.nuget/packages
      uses: actions/cache@v2
      with:
          path: |
            .nuke/temp
            ~/.nuget/packages
          key: ${{ runner.os }}-${{ hashFiles('**/global.json', '**/*.csproj') }}
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Run build
      run: ./build.sh BuildAndUnitTests --configuration Release
      
  integration:
    name: Build and run Integration Tests
    needs: [build]
    runs-on: ubuntu-latest       
    steps:
    - uses: actions/checkout@v3
    - name: Cache .nuke/temp, ~/.nuget/packages
      uses: actions/cache@v2
      with:
          path: |
            .nuke/temp
            ~/.nuget/packages
          key: ${{ runner.os }}-${{ hashFiles('**/global.json', '**/*.csproj') }}
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Run build
      run: ./build.sh RunAllIntegrationTests
