# Runs tests whenever a pull request is made

name: CI Pipeline

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened

jobs:
  tests:
    name: Build and run tests

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
  
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Run build
      run: ./build.sh RunCIBuild --configuration Release
